#
# Travis config
sudo: required
services:
  - docker 


before_install:
  - docker build -t thebungler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thebungler/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: "docker-react"
  env: "Murks-env"
  bucket_name: "elasticbeanstalk-eu-central-1-517192386284"
  bucket_path: "docker-react"
  on:
    branch: main 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY