#
# Travis config
sudo: required
services:
  - docker 


before_install:
  - docker build -t thebungler/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thebungler/docker-react npm run test 