version: '3'
services:
  devinst: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app

  testinst:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

  prodinst:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
      - .:/app